### ISSUE TITLE
Feature: Add a Movement block

### ISSUE THREAD

**Issue by SBird1337** [huderlem/poryscript#17]
There are several structures that are frequently used when writing Scripts, one of them in regards to the `applymovement` command.

The environment has to output it's contents directly to the assembly for the most part. Some features that would be nice to include:

 * Multiple statements at once with the multiplication (`*`) operator
 * Automatically closing movement blocks (though I don't know if PoryScript should "know" about how those blocks are usually ended)

e.g. with `raw`:
```
raw `
MyMove:
    walk_down
    walk_down
    step_end
`
```
with a movement block:
```
move MyMove {
    walk_down * 2
}
```

**Comment by huderlem** [comment]
1ca8e5802a4c7c3ae22b5ea4438a597870bfefc8
