### ISSUE TITLE
Allow local symbols to be defined

### ISSUE THREAD

**Issue by SBird1337** [huderlem/poryscript#21]
Currently PoryMap decides for you, which symbols are created locally, and which ones are created globally (`:` vs. `::` for `preproc`)

With regards to other environments, especially (#17 ) it may be desireable to have symbols globally, or locally. Same goes for text areas, which are currently global by default, and even strings. (Think of a small script you want to call multiple times from the local file)

**Comment by huderlem** [comment]
c9962c33cc5ebe833a81dd17ea8e1717e8905ff0
