### ISSUE TITLE
Inline strings not working correctly when they are not the first parameter

### ISSUE THREAD

**Issue by SBird1337** [huderlem/poryscript#25]
I don't know if this is the most accurate description, but here are steps to reproduce this bug:

 1. Create a script with a command which takes a text input as non-first parameter (see example)
 2. Observer that the text is rendered, but its pointer is not.

Example:

```poryscript
script TrainerschuleOutdoor_trainerbattle_vs_youngster {
	trainerbattle(TRAINER_BATTLE_SINGLE_NO_INTRO_TEXT, TRAINER_YOUNGSTER_TRAINERSCHOOL_OUTDOOR_SCRIPTFIGHT, 0, "Not another defeat!")
}
```

Playground: https://www.huderlem.com/poryscript-playground/?switches=LANG=EN%20GAME_VERSION=EMERALD&code=M4YwTglgDgLgBAFTAQwgOwKZlACwK4A2GA8njACYD2lYA+jCulgEbIwxG0BuwtAnpTxoA5sBhY4AbwBQASAapMYVuyIAKBACUAggEkAcgFFNtAELaECADKHaAZQMBxG7X3FaBre4SGAGggAaRB0DY1oATWIAVX1HOx8TLT0jTTsAYQAJYmIrWmiEABFsk3TNXQAFBAAxXUcMwLgABiCAIn1KeGQ0DpwJcgwAMww2AEIWgEppAF8gA

**Comment by huderlem** [comment]
Fixed: 7107d6678003c55388f6f5d037214c5e5191e0f0
