### ISSUE TITLE
Compiled script to PoryScript?

### ISSUE THREAD

**Issue by Dokman** [huderlem/poryscript#26]
is it posible?

**Comment by huderlem** [comment]
It's probably possible, to some extent.  Nothing has been built to do it, though, and it's not a goal of mine.  Might be a fun project for someone.

**Comment by Dokman** [comment]
i will try to learn how to script in go and i will try it idk how but i will try it

**Comment by huderlem** [comment]
Best of luck--if you make progress, post back here.  Closing this issue for now, since it's not an explicit goal for this project.
