### ISSUE TITLE
[Enchancement] Support a "label" command

### ISSUE THREAD

**Issue by Deokishisu** [huderlem/poryscript#49]
> One thing that has come up a handful of times that I would like to see from poryscript is the ability to put labels anywhere without defining a new script. While scripting there are a few very infrequent circumstances where being able to jump to an arbitrary point in a script without using one of the loops and without duplicating script segments is helpful.

- Me, from the Discord.

**Comment by huderlem** [comment]
This is now in `master`.  Before closing the issue, I'm waiting for confirmation that it works as expected and is actually useful.
