### ISSUE TITLE
Emitter stops at end / return statement.

### ISSUE THREAD

**Issue by SBird1337** [huderlem/poryscript#51]
Title. This is usually fine because it will end the current context, it is not fine in the context of labels: https://www.huderlem.com/poryscript-playground/?switches=LANG=EN%20GAME_VERSION=EMERALD&code=M4YwTglgDgLgBABQIZmAUzAZRgeysAQRgCU0YBXMAOzgG8AoOJuAcx1wAokQKkAbTOGgwAlI2ZgylKvW68BQ2AC5xTALbAWAIxwAPDgCIYACwjA4ZuFXZxJVACYY09g2IC+QA

It might also cause a problem with some fictional setting where the program skips over a return statement any other way. Generally I would expect anything I type to be rendered, even if it is generally unreachable.

**Comment by huderlem** [comment]
Fixes by 4393482cc233e860f5fa064218124e6bf7746a37
