### ISSUE TITLE
[Feature request] Improvements to the format utility

### ISSUE THREAD

**Issue by Jaizu** [huderlem/poryscript#57]
- [x] Take the arrow width into account, only when it's present
- [x] Config to change the px of the arrow itself, the FRLG one is narrower than the Emeralds, but I think we should support any width value since every project can have it's own
- [x] Option to force a line jump without having to specify \n or \l, because sometimes I just want a line jump and I don't know if it needs to be the first line jump or not

**Comment by huderlem** [comment]
Added in release 3.1.0 https://github.com/huderlem/poryscript/releases/tag/3.1.0
