### ISSUE TITLE
TOOLSDIRS variable is missing tools/poryscript in Makefile 

### ISSUE THREAD

**Issue by ChangedUser** [huderlem/poryscript#61]
Additionally to the Makefile changes that have been written down in the Usage Section, a necessary change of the TOOLSDIRS variable has been omitted. 

`-TOOLDIRS := $(filter-out tools/agbcc tools/binutils,$(wildcard tools/*))`
`+TOOLDIRS := $(filter-out tools/agbcc tools/binutils tools/poryscript,$(wildcard tools/*))`

**Comment by GriffinRichards** [comment]
(While I'm here) This can be closed, the current project Makefiles no longer require this. They now explicitly list the tools that should be built with Make.
