### ISSUE TITLE
Allow Video Playback

### ISSUE THREAD

**Issue by CallumPerry** [huderlem/poryscript#63]
GBA Video is a format for putting full color, full-motion videos onto Game Boy Advance ROM cartridges. With modern emulators, I assume we could add bigger and clearer videos into games.

I'd like to create a "Pokemon Channel" styled game with video cut scenes. There are so many episodes, movies and specials to utilize; i'm sure this could be something that would benefit the whole community.

From what I've already learned, you need to have .avi video files (with specific bitrate, frame rate and aspect ratio) inside a folder inside the src folder. I'd like to run a script so when the player interacts with an NPC, it will lock the player, play the video file, then release the player. It doesn't appear that the current set up allows GBA Video's to run, unless i'm mistaken?

https://gbatemp.net/threads/guide-how-to-convert-youtube-videos-to-game-boy-advance-rom-files.520954/
https://www.gameboy-advance.net/video

**Comment by huderlem** [comment]
Unfortunately this isn't something that Poryscript could be responsible for.  Poryscript is mostly syntactic sugar for the game's scripting capabilities.  To play a video like that, you'd need to make code changes to the game itself.  For example, you could create a new `playvideo` script command and then call that from a Poryscript script.

**Comment by CallumPerry** [comment]
Ok, thank you. I'll look into that!
