### ISSUE TITLE
permission denied?

### ISSUE THREAD

**Issue by moxhakk** [huderlem/poryscript#65]
i just installed poryscript following the readme steps and i also made a script on a new map, and then this happens, not sure why
![Captura de pantalla 2024-07-01 202721](https://github.com/huderlem/poryscript/assets/157393265/4021fbb5-7574-4b3d-a679-da1b0d9fbced)

**Comment by pkmnsnfrn** [comment]
> i just installed poryscript following the readme steps and i also made a script on a new map, and then this happens, not sure why ![Captura de pantalla 2024-07-01 202721](https://private-user-images.githubusercontent.com/157393265/344775564-4021fbb5-7574-4b3d-a679-da1b0d9fbced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTg4MDcsIm5iZiI6MTcxOTg1ODUwNywicGF0aCI6Ii8xNTczOTMyNjUvMzQ0Nzc1NTY0LTQwMjFmYmI1LTc1NzQtNGIzZC1hNjc5LWRhMWIwZDlmYmNlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQxODI4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTFhNGVkMGU2YjE1MTk2NjM2NTQwZTAwMjZjYmEwMDI2ZjAwNTZkOGY0MDhjNzBhM2YyMjA3MTk2YmNmY2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R7pQm5lV2zGSfhFc4dOeXVMsdkloqxzqc9kK5hh58dM)

What happens when you run `sudo chmod +x tools/poryscript/poryscript` and then `make` again?

**Comment by moxhakk** [comment]
wow thanks seems to work now, but from now on, do i have to type that everytime i open a console?

**Comment by pkmnsnfrn** [comment]
> wow thanks seems to work now, but from now on, do i have to type that everytime i open a console?

No, only when you reinstall / update poryscript.

**Comment by moxhakk** [comment]
okay i see, thank you so much really
