### ISSUE TITLE
.pory files considered "plain text" in VS Code

### ISSUE THREAD

**Issue by dinonight-official** [huderlem/poryscript#77]
Pretty much the title. All of my .pory files are considered Plain Text, and I have no idea how to change it. I followed a tutorial on youtube to set up poryscript, and it looks alright, but there is no poryscript file type I can format. Did I miss a step in downloading it? Is there some other way of changing all the files through the terminal?

**Comment by Jaizu** [comment]
We don't recommend any youtube guide, use the steps in provided in the README: https://github.com/huderlem/poryscript/blob/master/README.md
VSCode has this extension: https://marketplace.visualstudio.com/items?itemName=karathan.poryscript

**Comment by dinonight-official** [comment]
I had already scoured the read me and did everything I could. That extension did work though, so thank you for that!
